dist: trusty
sudo: required
language: generic

env:
  - DOCKER_COMPOSE_VERSION: 1.14.0

cache: yarn

before_install:
  # Install the latest version of Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -qq update
  - sudo apt-get install -qqy docker-ce
  # Install Docker Compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

before_script:
  - docker-compose up -d
  - docker-compose logs -f api | while read line; do
      echo $line;
      [[ $line == *"server is listening"* ]] && pkill -f "docker-compose logs -f api";
    done

script:
  - docker-compose exec api yarn lint
  - docker-compose exec api yarn test

after_script:
  - docker-compose down
